Repository PedroChaparro/PI202202-alako-frontend, pull requests merged in 2022-10, with the labels that each got.

#16 Links and responsive sizes
  src/index.html
  src/public/fonts/Inter-Medium.ttf
  src/script.js
  src/style.css
Labels: Hotfix

#17 Pull Request US 07
  src/index.html
  src/public/fonts/Inter-Medium.ttf
  src/public/fonts/Inter.ttf
  src/public/fonts/Inter.woff
  src/public/fonts/Inter.woff2
  src/script.js
  src/style.css
  src/vite.config.js
Labels: S3

#21 Update README.md
  README.md
Labels: documentation

#22 Final Deploy 🏁
  .eslintrc.json
  .gitignore
  .prettierrc.json
  package-lock.json
  package.json
  src/index.html
  src/main.js
  src/package-lock.json
  src/package.json
  src/public/fonts/Inter.ttf
  src/public/fonts/Inter.woff
  src/public/fonts/Inter.woff2
  src/public/icons/moon-icon.svg
  src/public/icons/play-icon.svg
  src/public/icons/search-icon.svg
  src/public/icons/sun-icon.svg
  src/public/images/1.png
  src/public/images/header-image.jpg
  src/script.js
  src/storage.js
  src/style.css
Labels: S2, S3
